name: Build Darwin

on:
  push:
    tags: 
      - v0.*
      - v0.*.*
  pull_request:
    tags:
      - v0.*
      - v0.*.*

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: ./tools/build_darwin.sh

    - name: Upload Release Assets
      uses: wzshiming/action-upload-release-assets@v1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

